59 Remove properties no longer used
AbsaOSS/hermes pull request #69
Opened 2020-04-20 19:26 UTC by Zejnilovic

Following #68, where some properties were removed, I updated the documentation.

2020-04-21 09:27 UTC, yruslan commented on _docs/0.2.0/usage.md
> +- `allowDuplicates` is switch to allow or disallow duplicate columns in comparisons. Duplicates will be ignored.
Duplicate columns or duplicate rows?

2020-04-21 09:46 UTC, Zejnilovic commented on _docs/0.2.0/usage.md
> +- `allowDuplicates` is switch to allow or disallow duplicate columns in comparisons. Duplicates will be ignored.
Rows. Nice catch 👍

2020-04-21 10:55 UTC, yruslan approved these changes

2020-04-21 22:12 UTC, benedeki requested changes

2020-04-21 22:12 UTC, benedeki commented on _docs/0.2.0/usage.md
> +- `allowDuplicates` is switch to allow or disallow duplicate rows in comparisons. Duplicates will be ignored.
```suggestion
- `allowDuplicates` is a switch to allow or disallow duplicate rows in comparisons; duplicates will be ignored
```

2020-04-22 09:24 UTC, benedeki approved these changes

2020-04-22 09:57 UTC, merged